version: 2.1
executors:
  exectr:
    docker:
      - image: FRPProject/inav-F411TE:latest
jobs:
  test:
    executor: exectr
    steps:
      - checkout
      - run:
          name: test
          command: |
            mkdir build
            cd build
            cmake ..
            make MATEKF411TE
workflows:
  test_my_app:
    jobs:
      - test