version: 2.1
orbs:
  ruby: circleci/ruby@2.0
executors:
  exectr:
    docker:
      - image: dockerben/cpptemplate:latest
jobs:
  test:
    executor: exectr
    docker:
      - image: cimg/ruby:2.7-node
    steps:
      - ruby/install-deps
      - checkout     
      - run:
          name: test
          command: |
            mkdir build
            cd build
            cmake ..
            make MATEKF411TE
workflows:
  test_my_app:
    jobs:
      - test