version: 2.1
orbs:
  win: circleci/windows@4.1.1 # The Windows orb gives you everything you need to start using the Windows executor

jobs:
  test: # name of your job
    executor: win/server-2022 # use one of the executors defined within the windows orb
    #executor: exectr
    steps:
      - checkout
      - run:
          name: test
          command: |
            mkdir build
            cd build
            cmake ..
            make MATEKF411TE
workflows:
  test_my_app:
    jobs:
      - test